#!/bin/bash

BADVARS="-u COLORFGBG \
    -u COLORTERM \
    -u CVS_RSH \
    -u CYGWIN \
    -u DISPLAY \
    -u EDITOR \
    -u HOSTNAME \
    -u LIBRARY \
    -u MAKE_MODE \
    -u OLDPWD \
    -u PAGER \
    -u PKG_CONFIG_PATH \
    -u PRINTER \
    -u PROMPT \
    -u PS1 \
    -u PWD \
    -u QMAKESPEC \
    -u QTDIR \
    -u SHLVL \
    -u TEXDOCVIEW_dvi \
    -u TEXDOCVIEW_html \
    -u TEXDOCVIEW_pdf \
    -u TEXDOCVIEW_ps \
    -u TEXDOCVIEW_txt \
    -u USER \
    -u VISUAL \
    -u WINDOWID \
    -u _"


# env $BADVARS PATH=/c/windows/system32:/c/other/svn-win32-1.4.2/bin:/c/borland/bin /bin/cygstart cmd "$@"

export PATH=/bin:$(cygpath -u "$SYSTEMROOT")/system32
export HOME="$PWD/staging"
export INFOPATH=/usr/info
export MANPATH=/usr/man
/bin/env $BADVARS /bin/bash --init-file staging/.bash_profile

