;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        barrkel-indent-shift-left
        barrkel-indent-shift-right
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        coffee-dedent-line-backspace
        coffee-indent-shift-left
        coffee-indent-shift-right
        coffee-newline-and-indent
        comment-or-uncomment-region
        company-complete
        dabbrev-expand
        delete-line-command
        dired-next-line
        dired-previous-line
        dumb-newline
        duplicate-line-or-region
        end-of-buffer
        end-of-visual-line
        enh-ruby-electric-brace
        fixup-whitespace
        haml-electric-backspace
        helm-M-x
        indent-for-tab-command
        insert-braces-macro
        isearch-abort
        isearch-backward-regexp
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-printing-char
        kill-region
        kill-visual-line
        overwrite-mode
        ruby-end-of-block
        scroll-down-line
        scroll-up-line
        subword-left
        subword-right
        wdired-downcase-word
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-done
        ace-jump-word-mode
        describe-key
        ido-find-file
        iedit-mode
        save-some-buffers
        toggle-word-highlight
        wdired-finish-edit
        wgrep-finish-edit
        ))
