;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        coffee-dedent-line-backspace
        coffee-newline-and-indent
        dabbrev-expand
        delete-line-command
        duplicate-line-or-region
        end-of-visual-line
        end-of-visual-line
        fixup-whitespace
        indent-for-tab-command
        kill-region
        kill-visual-line
        overwrite-mode
        scroll-down-line
        scroll-up-line
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        wgrep-finish-edit
        ))
